# YAML configuration file for running VSLAM with Kitti Dataset Sequence 00
dataset:
    type: "KittiDataloader"
    args:
        path: "/home/akashsharma/Documents/datasets/kitti/odometry/"
        sequence: "00"
save_dir: "logs/"

