feature: 
    type: "SuperPointFeatureExtractor"
    args:
        weights_path: "/home/alex/GitHub_dev/visual-slam/vslam/feature/SuperPointPretrainedNetwork/superpoint_v1.pth"
        img_h: 120
        img_w: 160
        nms_dist: 4
        conf_thresh:  0.015
        nn_thresh: 0.7
        cuda: False